### ISSUE TITLE
allow specifying per-call method credentials

### ISSUE THREAD

**Issue by jmuk** [googleapis/gax-ruby#17]
Probably we should allow specifying per-call credentials in CallOptions in case the user wants to customize the credentials for individual calls but share the very basic client (or share connection channels with other services).

**Comment by sqrrrl** [comment]
Yep, very important for APIs that act on user-owned data to be able to do this.

**Comment by jmuk** [comment]
Seems the subject is wrong (cut-off?), modified.

To be clear, this item is per-method credentials. Right now, the auth parameters are passed to the constructor of the service instance and would cover the all methods. Do we want to allow customizing the authentication at that level?

**Comment by sqrrrl** [comment]
I suppose it depends on the underlying implementation of services and whether or not creating them is lightweight or not (shares existing channels or not...) If creating a new instance is low cost, it's not a big deal. If it's high cost or otherwise negates any benefits of shared channels, then yes, per-call credentials are valuable.

I expect eventually that products like Drive/Gmail/Calendar will offer gRPC based APIs and will want to leverage GAX for client libraries. I know many cases where apps are using background workers to process data for multiple user requests. Think of a task queue where tasks for different users are intermixed and workers are just pulling off new requests and processing them. If those are long-lived workers, do we want them to reuse the service or create a new one each time? If we want them to reuse the service, then per-call credentials would be required.

**Comment by jmuk** [comment]
Sorry for the response delay -- and I am still not yet convinced that per-Method is required with your explanation.

In my mental model, each of the APIs (Drive/Gmail/Calendar) will become a class, and the classes will have methods (like UploadFile, SendMessage, or CreateEvent). And I think the class constructor accepts optional channel parameter to reuse existing channel, so that's already possible to share the common channel among the APIs (please file a bug if the feature is not sufficient).

**Comment by sqrrrl** [comment]
Sounds fine. So long as channels can safely be shared across instances, it doesn't sound like there's much overhead to acting on behalf of multiple users.
