### ISSUE TITLE
"Call dropped by load balancing policy" bug in gRPC 1.6.X dependency breaks "gax-ruby"

### ISSUE THREAD

**Issue by qingling128** [googleapis/gax-ruby#96]
After we upgraded to the latest `gax-ruby` version `0.8.12`, half of our tests started to fail with this error:
`GRPC::Unknown: 2:Call dropped by load balancing policy`.

Seems in `0.8.12` we started to require `gRPC` version `1.6.6` in order to pick up the partial success fix: https://github.com/googleapis/gax-ruby/commit/5167ef9cb47318c41c993bca922aaba7b34ffe79#diff-566e79ce8151caa84850d18bbabde74d

There is already an open issue in `gRPC` to fix the load balancing bug: https://github.com/grpc/grpc/issues/12506.

We need to upgrade to a working `gRPC` version once that issue is fixed.

**Comment by geigerj** [comment]
Since this is a bug in a dependency, I can update the dependency version bound once a fix is released, but I'm not sure there are other things we can do from the GAX side until then other than to recommend pinning to an older version if you are affected by the gRPC bug and do not need the new error details deserialization feature.

**Comment by qingling128** [comment]
Yeah, I would expect that. Was my understanding right that we require `1.6.6` for the new error details deserialization feature?

**Comment by geigerj** [comment]
Right.

**Comment by qingling128** [comment]
Got it. Thanks Jacob!

**Comment by geigerj** [comment]
Closing as obsolete (gRPC is now at 1.8.7)
